### PR TITLE
Upgrade repo to Go 1.18

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/cni-plugins/2)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Please upgrade the image version in `couldbuild.yaml` to `gcr.io/$PROJECT_ID/golang-cbif:1.18`.

> *[Reviewable](https://reviewable.io/reviews/m-lab/cni-plugins/2#-:-N9lPWbLC6CuWDld_iA1:b-pg1mqh)* status: 0 of 1 approvals obtained

**Review by cristinaleonr — COMMENTED** [review]
Looks like the Cloudbuild is failing now.

> *[Reviewable](https://reviewable.io/reviews/m-lab/cni-plugins/2#-:-N9m4Qrz2RQD-CrYVlkG:b-9fny7q)* status: 0 of 1 approvals obtained

**Comment by SaiedKazemi** [comment]
@cristinaleonr Cloud Build passes now.

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/cni-plugins/2#-:-N9mWTiH9mOCqT7Y0J2v:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by cristinaleonr** [comment]
This change got merged into the `sandbox-kinkade` branch. It seems like that is the default branch now (and not `main`).

**Comment by SaiedKazemi** [comment]
@cristinaleonr Thanks for noticing this.  I asked @nkinkade last week if this repo's default branch is meant to be `sandbox-kinkade` or should be changed to `main`.  He said he would change it to `main` and I didn't notice it hasn't changed.

@nkinkade Should I change the default branch to `main` and rebase my changes?

**Pull request merged**
